-- Run as scoringsys_migrator after all schema migrations.
REVOKE ALL ON SCHEMA public FROM scoringsys_app;
GRANT USAGE ON SCHEMA public TO scoringsys_app;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM scoringsys_app;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM scoringsys_app;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM scoringsys_app;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM PUBLIC;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO scoringsys_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO scoringsys_app;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO scoringsys_app;

ALTER DEFAULT PRIVILEGES FOR ROLE scoringsys_migrator IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO scoringsys_app;
ALTER DEFAULT PRIVILEGES FOR ROLE scoringsys_migrator IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO scoringsys_app;
ALTER DEFAULT PRIVILEGES FOR ROLE scoringsys_migrator IN SCHEMA public
  GRANT EXECUTE ON FUNCTIONS TO scoringsys_app;
ALTER DEFAULT PRIVILEGES FOR ROLE scoringsys_migrator IN SCHEMA public
  REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
