'use client';

import { useState } from 'react';

export default function MeetingRecycleBin({ meetings, onRestore, onBack }: { meetings: Record<string, any>[]; onRestore: (ids: string[]) => void; onBack: () => void }) {
  const [selected, setSelected] = useState<string[]>([]);
  const toggle = (id: string) => setSelected((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]);
  const restore = (ids: string[]) => ids.length && window.confirm(`恢复 ${ids.length} 场评审会？`) && onRestore(ids);
  return <section style={{ marginTop: 20 }}><div style={styles.toolbar}><div><button style={styles.secondary} onClick={onBack}>返回列表</button><h2 style={{ margin: '12px 0 0', fontSize: 18 }}>评审会回收站</h2></div>{selected.length > 0 && <button style={styles.primary} onClick={() => restore(selected)}>恢复所选</button>}</div><p style={styles.help}>回收评审会不会清除项目、评分或报告历史。</p><div style={styles.wrap}><table style={styles.table}><thead><tr><th style={styles.cell}><input aria-label="全选回收站评审会" type="checkbox" checked={meetings.length > 0 && selected.length === meetings.length} onChange={() => setSelected(selected.length === meetings.length ? [] : meetings.map((meeting) => meeting.id))}/></th><th style={styles.cell}>评审会</th><th style={styles.cell}>回收时间</th><th style={styles.cell}>操作</th></tr></thead><tbody>{meetings.map((meeting) => <tr key={meeting.id}><td style={styles.cell}><input aria-label={`选择${meeting.name}`} type="checkbox" checked={selected.includes(meeting.id)} onChange={() => toggle(meeting.id)}/></td><td style={styles.cell}>{meeting.name}</td><td style={styles.cell}>{meeting.deleted_at ? new Date(meeting.deleted_at).toLocaleString('zh-CN') : '-'}</td><td style={styles.cell}><button style={styles.primary} onClick={() => restore([meeting.id])}>恢复</button></td></tr>)}{!meetings.length && <tr><td colSpan={4} style={{ ...styles.cell, textAlign: 'center', color: '#64748b' }}>回收站为空</td></tr>}</tbody></table></div></section>;
}

const styles: Record<string, React.CSSProperties> = { toolbar: { display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'center' }, help: { color: '#64748b', fontSize: 13 }, primary: { background: '#0f766e', color: '#fff', border: '1px solid #0f766e', borderRadius: 5, padding: '8px 12px', cursor: 'pointer' }, secondary: { background: '#fff', color: '#334155', border: '1px solid #cbd5e1', borderRadius: 5, padding: '8px 12px', cursor: 'pointer' }, wrap: { overflowX: 'auto', border: '1px solid #d9e1ec', borderRadius: 6 }, table: { width: '100%', borderCollapse: 'collapse' }, cell: { padding: '11px 12px', textAlign: 'left', borderBottom: '1px solid #e7edf5' } };
