type Report = Record<string, any>;

const verdictLabel = (value: string) => ({ approved: '通过', recheck: '待重评', rejected: '驳回' } as Record<string, string>)[value] || '待 Walker 结论';
const number = (value: unknown) => Number(value || 0).toFixed(1);
const dateTime = (value: unknown) => value ? String(value).replace('T', ' ').slice(0, 16) : '-';

export default function RoundOneReport({ report }: { report: Report }) {
  return <ReportTable title="第一轮评审报告" subtitle="游戏性与创新性评审" report={report} dimensions={['游戏性', '创新性']} />;
}

export function ReportTable({ title, subtitle, report, dimensions }: { title: string; subtitle: string; report: Report; dimensions: string[] }) {
  const projects = report?.projects || [];
  const reviewers = (report?.reviewers || []).filter((reviewer: Report) => !reviewer.is_admin);
  const verdicts = projects.reduce((total: Record<string, number>, project: Report) => { total[project.verdict] = (total[project.verdict] || 0) + 1; return total; }, {});
  const average = projects.length ? projects.reduce((total: number, project: Report) => total + Number(project.totalScore || 0), 0) / projects.length : 0;
  return <article style={styles.page}>
    <header style={styles.header}><div><p style={styles.kicker}>REVIEW MEETING REPORT</p><h1 style={styles.h1}>{title}</h1><p style={styles.subtle}>{subtitle}</p></div><div style={styles.meetingMeta}><strong>{report?.meeting?.name || '未命名评审会'}</strong><span>会议日期：{dateTime(report?.meeting?.meeting_date)}</span><span>评分截止：{dateTime(report?.meeting?.deadline)}</span></div></header>
    <section style={styles.summaryGrid}><Metric label="纳入排名项目" value={`${projects.length} 个`} /><Metric label="平均总分" value={`${number(average)} / 100`} /><Metric label="通过" value={`${verdicts.approved || 0} 个`} tone="#0f766e" /><Metric label="待重评 / 驳回" value={`${verdicts.recheck || 0} / ${verdicts.rejected || 0}`} tone="#b45309" /></section>
    <section style={styles.meetingNote}><strong>评审会说明</strong><span>{report?.meeting?.notes || '无会议备注'}</span></section>
    <section><h2 style={styles.h2}>项目排名与维度对比</h2><div style={styles.tableWrap}><table style={styles.table}><thead><tr><th>排名</th><th>项目</th><th>总分</th>{dimensions.map((name) => <th key={name}>{name}</th>)}<th>完成度</th><th>Walker 结论</th></tr></thead><tbody>{projects.map((project: Report) => <tr key={project.id}><td style={styles.rank}>{project.rank || '-'}</td><td><strong>{project.name}</strong><br/><small>{project.submitter || '-'}</small></td><td><strong>{number(project.totalScore)} / {project.totalMaxScore || 100}</strong>{Number(project.bonusScore || 0) ? <small style={styles.bonus}>加分 {number(project.bonusScore)}</small> : null}</td>{dimensions.map((name) => <DimensionCell key={name} item={project.dimTotals?.[name]} />)}<td>{project.completionRate || 0}%</td><td><strong>{verdictLabel(project.verdict)}</strong></td></tr>)}{!projects.length && <tr><td colSpan={dimensions.length + 5} style={styles.empty}>本轮没有已确认 Walker 结论的项目。</td></tr>}</tbody></table></div></section>
    <section><h2 style={styles.h2}>问题、行动与评审依据</h2><div style={styles.detailGrid}>{projects.map((project: Report) => <article key={project.id} style={styles.projectDetail}><div style={styles.detailHeading}><div><strong>#{project.rank || '-'} {project.name}</strong><span>{number(project.totalScore)} / {project.totalMaxScore || 100} · {verdictLabel(project.verdict)}</span></div><span>{project.completionRate || 0}% 完成</span></div><div style={styles.dimensionRows}>{dimensions.map((name) => <DimensionBar key={name} name={name} item={project.dimTotals?.[name]} />)}</div><div style={styles.issueRows}><div><strong>主要问题</strong><p>{project.problemSummary || flatten(project.reviewerProblems, 'problems') || '无'}</p></div><div><strong>改进行动</strong><p>{project.actionSummary || flatten(project.reviewerActions, 'actions') || '无'}</p></div></div></article>)}{!projects.length && <p style={styles.muted}>暂无可展示的项目明细。</p>}</div></section>
    <section><h2 style={styles.h2}>评委参与与完成情况</h2><div style={styles.tableWrap}><table style={styles.table}><thead><tr><th>评委</th><th>角色</th><th>已填写项</th><th>应填写项</th><th>完成率</th></tr></thead><tbody>{reviewers.map((reviewer: Report) => { const expected = Number(reviewer.expectedScores || 0); const given = Number(reviewer.scoresGiven || 0); return <tr key={reviewer.code}><td>{reviewer.name || reviewer.code}</td><td>{reviewer.role || '-'}</td><td>{given}</td><td>{expected}</td><td>{expected ? `${Math.round(given / expected * 100)}%` : '-'}</td></tr>; })}{!reviewers.length && <tr><td colSpan={5} style={styles.empty}>暂无评委完成情况。</td></tr>}</tbody></table></div></section>
  </article>;
}

function Metric({ label, value, tone = '#172033' }: { label: string; value: string; tone?: string }) { return <div style={styles.metric}><span>{label}</span><strong style={{ color: tone }}>{value}</strong></div>; }
function DimensionCell({ item }: { item: Report }) { const score = Number(item?.score || 0); const max = Number(item?.maxScore || item?.max || 0); return <td>{number(score)} / {max || '-'}<div style={styles.track}><i style={{ ...styles.bar, width: `${max ? Math.min(100, score / max * 100) : 0}%` }} /></div></td>; }
function DimensionBar({ name, item }: { name: string; item: Report }) { const score = Number(item?.score || 0); const max = Number(item?.maxScore || item?.max || 0); return <div style={styles.dimension}><div style={styles.dimensionLine}><span>{name}</span><strong>{number(score)} / {max || '-'}</strong></div><div style={styles.track}><i style={{ ...styles.bar, width: `${max ? Math.min(100, score / max * 100) : 0}%` }} /></div></div>; }
function flatten(entries: Report[], key: 'problems' | 'actions') { return (entries || []).flatMap((entry) => entry[key] || []).filter(Boolean).join('；'); }

const styles: Record<string, React.CSSProperties> = {
  page: { maxWidth: 1120, margin: '0 auto', padding: 32, background: '#fff', color: '#172033', fontFamily: 'Arial, "Microsoft YaHei", sans-serif' }, header: { display: 'flex', justifyContent: 'space-between', gap: 24, alignItems: 'flex-start', borderBottom: '3px solid #0f766e', paddingBottom: 20 }, kicker: { color: '#0f766e', margin: '0 0 7px', fontSize: 12, fontWeight: 700, letterSpacing: 1 }, h1: { margin: 0, fontSize: 30 }, h2: { margin: '28px 0 12px', fontSize: 18 }, subtle: { margin: '8px 0 0', color: '#52606d' }, meetingMeta: { minWidth: 230, display: 'grid', gap: 6, padding: 13, background: '#f0fdfa', border: '1px solid #b7d9d5', fontSize: 13 }, summaryGrid: { display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0, 1fr))', gap: 12, marginTop: 18 }, metric: { display: 'grid', gap: 7, padding: 14, border: '1px solid #d9e1ec', background: '#fbfdff' }, meetingNote: { display: 'grid', gap: 6, marginTop: 12, padding: 14, background: '#f8fafc', borderLeft: '4px solid #0f766e', fontSize: 13 }, tableWrap: { overflowX: 'auto', border: '1px solid #d9e1ec' }, table: { width: '100%', borderCollapse: 'collapse', fontSize: 13 }, rank: { color: '#0f766e', fontWeight: 700 }, empty: { padding: 20, textAlign: 'center', color: '#64748b' }, bonus: { display: 'block', color: '#b45309', marginTop: 4 }, track: { height: 6, marginTop: 6, background: '#e7edf2' }, bar: { display: 'block', height: '100%', background: '#0f766e' }, detailGrid: { display: 'grid', gap: 12 }, projectDetail: { border: '1px solid #d9e1ec', padding: 16 }, detailHeading: { display: 'flex', justifyContent: 'space-between', gap: 16, alignItems: 'start' }, dimensionRows: { display: 'grid', gridTemplateColumns: 'repeat(3, minmax(0, 1fr))', gap: 12, margin: '14px 0' }, dimension: { display: 'grid', gap: 4 }, dimensionLine: { display: 'flex', justifyContent: 'space-between', gap: 8, fontSize: 13 }, issueRows: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14, paddingTop: 12, borderTop: '1px solid #e7edf2', fontSize: 13 }, muted: { color: '#64748b' }
};
